#!/usr/bin/env ruby
# frozen_string_literal: true

ADDRESSES = [
  '7. juni-plassen',
  'Abbediengen terrasse',
  'Abbediengveien',
  'Abbedikollen',
  'Abbedisvingen',
  'Abildsøfaret',
  'Abildsøveien',
  'Adam Hiorths vei',
  'Admiral Børresens vei',
  'Adolf Hedins vei',
  'Adventveien',
  'Advokat Dehlis plass',
  'Agathe Grøndahls gate',
  'Agdergata',
  'Agmund Bolts vei',
  'Agnes Thorsens plass',
  'Agronomveien',
  'Akebakkeskogen',
  'Akerlia',
  'Akersbakken',
  'Akersborg terrasse',
  'Akersgata',
  'Akershusstranda',
  'Akersveien',
  'Akevittsvingen',
  'Albert Nordengens plass',
  'Alexander Kiellands plass',
  'Alf Bjerckes vei',
  'Alfaset 1. industrivei',
  'Alfaset 3. industrivei',
  'Alfasetveien',
  'Alfred Groruds vei',
  'Almeveien',
  'Alnabruveien',
  'Alnafetgata',
  'Alnagata',
  'Alnaparkveien',
  'Alundamveien',
  'Alunsjøveien',
  'Alvheimveien',
  'Amagerveien',
  'Amaldus Nielsens plass',
  'Ammerudgrenda',
  'Ammerudhellinga',
  'Ammerudveien',
  'Amtmann Furus plass',
  'Amtmann Meinichs gate',
  'Amund Hellands vei',
  'Andreas Kremmers vei',
  'Ankertorget',
  'Ankerveien',
  'Anna Pleyms vei',
  'Anna Rogstads vei',
  'Anna Sethnes gate',
  'Anne Brannfjelds vei',
  'Anne Kures sti',
  'Anne Maries vei',
  'Annette Thommessens plass',
  'Ansgar Sørlies vei',
  'Antenneveien',
  'Anton Schjøths gate',
  'Anton Tschudis vei',
  'Apalløkkveien',
  'Apalveien',
  'Apotekergata',
  'Arbeidergata',
  'Arbeidersamfunnets plass',
  'Arbins gate',
  'Arbos gate',
  'Arctanders gate',
  'Arendalsgata',
  'Arilds vei',
  'Arildsvingen',
  'Arkitekt Rivertz\' plass',
  'Arkitekt Steckmests vei',
  'Armauer Hansens gate',
  'Arnebråtveien',
  'Arne Garborgs plass',
  'Arne Garborgs vei',
  'Arne Gjestis plass',
  'Arnes vei',
  'Arnljot Gellines vei',
  'Arno Bergs plass',
  'Arnstein Arnebergs vei',
  'Arnulf Øverlands vei',
  'Arthur Nordlies vei',
  'Arups gate',
  'Arvesetveien',
  'Arvid Storsveens plass',
  'Asalveien',
  'Asbjørnsens vei',
  'Aschehougs vei',
  'Askekroken',
  'Askeladdveien',
  'Askergata',
  'Askeveien',
  'Aslakveien',
  'Aslaug Vaas veg',
  'Aspehaugveien',
  'Asperudlia',
  'Asperudtoppen',
  'Asperudveien',
  'Asperudåsen',
  'Aspestien',
  'Astrids vei',
  'Aud Schønemanns vei',
  'August Cappelens gate',
  'Aurskoggata',
  'Austliveien',
  'Avlangruds vei',
  'Avstikkeren',
  'Axel Brinchs vei',
  'Axel Flinders vei',
  'Axel Huitfeldts vei',
  'Badebakken',
  'Badstugata',
  'Baglerfaret',
  'Baglerstredet',
  'Bakkehaugveien',
  'Bakkerudveien',
  'Bakketoppen',
  'Bakkeveien',
  'Bakveien',
  'Balchens gate',
  'Balders gate',
  'Ballplassveien',
  'Bamseveien',
  'Baneveien',
  'Bankplassen',
  'Banksjef Frølichs gate',
  'Barliveien',
  'Barnehjemsveien',
  'Barnålveien',
  'Bauneveien',
  'Beddingen',
  'Bedriftsveien',
  'Behrens\' gate',
  'Beiteveien',
  'Bekkefaret',
  'Bekkelagsterrassen',
  'Bekkelagsveien',
  'Bekkelibakken',
  'Bekkelikroken',
  'Bekkelistubben',
  'Bekkeliveien',
  'Bekkenstenveien',
  'Bekkeveien',
  'Bekkevollveien',
  'Belgerudveien',
  'Benneches gate',
  'Bentsebrugata',
  'Bentsegata',
  'Benveien',
  'Bergendalsveien',
  'Bergensgata',
  'Bergensveien',
  'Bergkrystallen',
  'Bergljots vei',
  'Berglyveien',
  'Bergrådveien',
  'Bergsalléen',
  'Bergslia',
  'Bergsliens gate',
  'Bergstien',
  'Bergtunveien',
  'Bergverksgata',
  'Bernhard Getz\' gate',
  'Bernhard Herres vei',
  'Bernhusveien',
  'Bernt Ankers gate',
  'Bernt Knudsens vei',
  'Bertramjordet',
  'Bertrand Narvesens vei',
  'Bervens løkke',
  'Bestemorstien',
  'Bestum skolevei',
  'Bestum tverrvei',
  'Bestumstubben',
  'Bestumveien',
  'Bestumåsen',
  'Betzy Kjelsbergs vei',
  'Beverkollen',
  'Beverveien',
  'Bidenkaps gate',
  'Biermanns gate',
  'Bikuben',
  'Bilittkroken',
  'Binneveien',
  'Birch-Reichenwalds gate',
  'Birger Olivers vei',
  'Birger Aaneruds vei',
  'Birgitte Hammers vei',
  'Birkelunden',
  'Biskop Grimelunds vei',
  'Biskop Gunnerus\' gate',
  'Biskop Heuchs vei',
  'Biskop Jens Nilssøns gate',
  'Bislettgata',
  'Bislett plass',
  'Bisp Nikolas\' gate',
  'Bispegata',
  'Bispeluelia',
  'Bjartveien',
  'Bjerkastien',
  'Bjerkealléen',
  'Bjerkebakken',
  'Bjerkefaret',
  'Bjerkelia',
  'Bjerkeliveien',
  'Bjerkelundgata',
  'Bjerregaards gate',
  'Bjerringbakken',
  'Bjølsengata',
  'Bjørkehavna',
  'Bjørn Bondes vei',
  'Bjørndalsjordet',
  'Bjørn Farmanns gate',
  'Bjørn Lies vei',
  'Bjørn Magnussons vei',
  'Bjørn Stallares vei',
  'Bjørnefaret',
  'Bjørnehiet',
  'Bjørnerabben',
  'Bjørnerudveien',
  'Bjørnheimveien',
  'Bjørnslettstubben',
  'Bjørnslettveien',
  'Bjørnstadbakken',
  'Bjørnstjerne Bjørnsons plass',
  'Bjørnveien',
  'Bjørnåsveien',
  'Blakkens vei',
  'Bleikøya',
  'Blindernveien',
  'Blokkaveien',
  'Blytts gate',
  'Blåbærsvingen',
  'Blåsbortveien',
  'Blåskjellveien',
  'Bodøgata',
  'Bogerudslyngen',
  'Bogerudveien',
  'Bogstadveien',
  'Bolette brygge',
  'Bolteløkka allé',
  'Bomveien',
  'Borgenbakken',
  'Borgenveien',
  'Borger Withs gate',
  'Borgestadveien',
  'Borggata',
  'Brageveien',
  'Brandts gate',
  'Brannfjellveien',
  'Brannvaktveien',
  'Brantenborgveien',
  'Brattbakken',
  'Brattelia',
  'Brattlistubben',
  'Brattoddveien',
  'Brattvollveien',
  'Bredes vei',
  'Bredo Stabells vei',
  'Bredtvetveien',
  'Bregneveien',
  'Breidablikkveien',
  'Breiens vei',
  'Breigata',
  'Breisjåveien',
  'Breivollveien',
  'Brekkelia',
  'Brekkeveien',
  'Brennagrenda',
  'Brennastubben',
  'Brennaveien',
  'Brenneriveien',
  'Brettevilles gate',
  'Brinken',
  'Briskebyveien',
  'Briskeveien',
  'Brobekkveien',
  'Brochmanns gate',
  'Brolandsveien',
  'Brubakkveien',
  'Brugata',
  'Brunas vei',
  'Bryggegangen',
  'Bryggegata',
  'Bryggetorget',
  'Brynjeveien',
  'Brynjulf Bulls plass',
  'Brynsalléen',
  'Brynsengfaret',
  'Brynsengveien',
  'Brynshøgda',
  'Brynsveien',
  'Brønnveien',
  'Bråtenalléen',
  'Bueveien',
  'Bukken Bruses vei',
  'Bygdøy allé',
  'Bygdøy kapellvei',
  'Bygdøy terrasse',
  'Bygdøylund',
  'Bygdøynesveien',
  'Bygdøyveien',
  'Byggveien',
  'Bülow Hanssens plass',
  'Byveien',
  'Bærumsveien',
  'Bøgata',
  'Bøkkerveien',
  'Bølerbakken',
  'Bølerlia',
  'Bølerskogen',
  'Bølerskrenten',
  'Bølersletta',
  'Bølersvingen',
  'Bølerveien',
  'Børrestuveien',
  'Børsteveien',
  'Båhusveien',
  'Bålveien',
  'Bånkallstubben',
  'Båntjernveien',
  'Bård Skolemesters vei',
  'C.A. Pihls gate',
  'C.A. Torstensens vei',
  'Calmeyers gate',
  'Camilla Colletts vei',
  'Cappelens vei',
  'Carl Berners plass',
  'Carl Grøndahls vei',
  'Carl Jeppesens gate',
  'Carl Kjelsens vei',
  'Caspar Storms vei',
  'Casparis gate',
  'Cathinka Guldbergs plass',
  'Cato Guldbergs vei',
  'Cecilie Thoresens vei',
  'Charlotte Andersens vei',
  'Christian Benneches vei',
  'Christian Frederiks plass',
  'Christian Frederiks vei',
  'Christian Krohgs gate',
  'Christian Michelsens gate',
  'Christian Schous vei',
  'Christiania Torv',
  'Christies gate',
  'Christoffer Hellums vei',
  'Christopher Hansteens vei',
  'Christophers vei',
  'C.J. Hambros plass',
  'Claus Borchs vei',
  'Claus Riis\' gate',
  'Clemens\' gate',
  'Colbjørnsens gate',
  'Colletts gate',
  'Conrad Hemsens vei',
  'Conradis gate',
  'Cort Adelers gate',
  'Dag Hammarskjølds vei',
  'Dagalikroken',
  'Dagaliveien',
  'Dagmarbakken',
  'Dalastien',
  'Dalbakkveien',
  'Dalehaugen',
  'Dalerudveien',
  'Dalheimveien',
  'Dalsbergstien',
  'Dalskroken',
  'Dalsløkka',
  'Dalsnaret',
  'Dalsroa',
  'Dalssvingen',
  'Dalsveien',
  'Dalsåsen',
  'Damfaret',
  'Damkroken',
  'Damlihaugen',
  'Damliveien',
  'Dammanns vei',
  'Damplassen',
  'Damstredet',
  'Damveien',
  'Daniel Walstads vei',
  'Danmarks gate',
  'Dannevigsveien',
  'Darre-Jenssens plass',
  'Darres gate',
  'Deichmans gate',
  'Delebekken',
  'Diakonveien',
  'Diriks\' gate',
  'Disengrenda',
  'Disenveien',
  'Dokkveien',
  'Doktor Baches vei',
  'Doktor Holms vei',
  'Doktor Kloumanns vei',
  'Doktor Londons vei',
  'Doktor Rustads vei',
  'Doktor Smiths vei',
  'Dops gate',
  'Dorthes vei',
  'Dovregata',
  'Dovresvingen',
  'Dr. Dedichens vei',
  'Dragonstien',
  'Drammensveien',
  'Drivhusveien',
  'Dronning Astrids gate',
  'Dronning Blancas vei',
  'Dronning Eufemias gate',
  'Dronning Ingrids plass',
  'Dronning Mauds gate',
  'Dronning Margretes vei',
  'Dronningen',
  'Dronningens gate',
  'Dronninghavnveien',
  'Drøbakgata',
  'Dråga',
  'Duehaugveien',
  'Duggveien',
  'Dugnadsveien',
  'Dunkers gate',
  'Dybwads gate',
  'Dyna brygge',
  'Dynekilgata',
  'Dyretråkket',
  'Dyrlandsveien',
  'Dyvekes vei',
  'Dælenenggata',
  'Dølerudveien',
  'Daas gate',
  'Ebbells gate',
  'Eckersbergs gate',
  'Eddaveien',
  'Edmund Neuperts gate',
  'Edvard Griegs allé',
  'Edvard Munchs vei',
  'Edvard Storms gate',
  'Eftasåsen',
  'Egedes gate',
  'Egertorget',
  'Egnehjemveien',
  'Egon Olsens allé',
  'Eidsvolls plass',
  'Eikelundveien',
  'Eikenga',
  'Eikeveien',
  'Eilert Smiths vei',
  'Eilert Sundts gate',
  'Einar Gerhardsens plass',
  'Einar Høigårds vei',
  'Einar Skjæraasens vei',
  'Einar Tambarskjelves plass',
  'Einars vei',
  'Eindrides vei',
  'Einerveien',
  'Eirik Raudes vei',
  'Eiriks gate',
  'Eivind Astrups gate',
  'Ekebergstien',
  'Ekebergveien',
  'Ekelyveien',
  'Ekornveien',
  'Ekraveien',
  'Elgtråkket',
  'Elgveien',
  'Elias Blix\' gate',
  'Elisa Platous plass',
  'Elisenbergveien',
  'Ellefs vei',
  'Ellen Gleditsch\' vei',
  'Ellingsrudveien',
  'Elmholt allé',
  'Elmholtveien',
  'Elsters gate',
  'Eltonveien',
  'Elvefaret',
  'Elveliveien',
  'Elverumgata',
  'Emil Korsmos vei',
  'Enebakkveien',
  'Enebostubben',
  'Eneboveien',
  'Enerhauggata',
  'Enerhaugkleiva',
  'Enerhaugplassen',
  'Engebrets vei',
  'Engebråtveien',
  'Engveien',
  'Enoks vei',
  'Ensjøsvingen',
  'Ensjøveien',
  'Erich Mogensøns vei',
  'Erika Nissens gate',
  'Erik Schias plass',
  'Erlandstuveien',
  'Erlends vei',
  'Erling Michelsens vei',
  'Erling Schiøtz\' vei',
  'Erling Skjalgssons gate',
  'Erlings gate',
  'Essendrops gate',
  'Eterveien',
  'Etterstadgata',
  'Etterstadkroken',
  'Etterstadsletta',
  'Eugene Hanssens gate',
  'Eugenies gate',
  'Europarådets plass',
  'Eva Kolstads gate',
  'Evald Ryghs gate',
  'Evald Ryghs plass',
  'Evens gate',
  'Eventyrveien',
  'Eystein Torkildsens vei',
  'Fabrikkgata',
  'Fabritiusalléen',
  'Fagerborggata',
  'Fagerheimgata',
  'Fagerlia',
  'Fagerlitrappa',
  'Fagerliveien',
  'Fagertunveien',
  'Fahlstrøms terrasse',
  'Falbes gate',
  'Falck Ytters plass',
  'Fallanveien',
  'Falsens gate',
  'Fastings gate',
  'Fauchalds gate',
  'Faunveien',
  'Fayes gate',
  'Fearnleys gate',
  'Feddersens gate',
  'Feltspatveien',
  'Fernanda Nissens gate',
  'Festningsplassen',
  'Fetsundgata',
  'Filerveien',
  'Filips gate',
  'Filipstad brygge',
  'Filipstadveien',
  'Finn Alexanders plass',
  'Finnhaugveien',
  'Finnmarkgata',
  'Finns vei',
  'Fiolveien',
  'Firkløverveien',
  'Fiskekroken',
  'Fisker Syversens vei',
  'Fjeldhøikroken',
  'Fjellgata',
  'Fjellhus allé',
  'Fjellhøiveien',
  'Fjellklangveien',
  'Fjellknattveien',
  'Fjellstien',
  'Fjellstuveien',
  'Fjordalléen',
  'Fjordgløttveien',
  'Fjordveien',
  'Fjørtofts gate',
  'Flaengrenda',
  'Flaenveien',
  'Flatengen',
  'Flesåstunet',
  'Flesåsveien',
  'Florabakken',
  'Flyveien',
  'Folke Bernadottes vei',
  'Folkvangveien',
  'Formerveien',
  'Forskningsveien',
  'Fossefaret',
  'Fossilveien',
  'Fossumberget',
  'Fossumkroken',
  'Fossumveien',
  'Fossveien',
  'Fougners vei',
  'Fougstads gate',
  'Framnes terrasse',
  'Framnesveien',
  'Framveien',
  'Frantzebråtveien',
  'Fred Olsens gate',
  'Fredensborgveien',
  'Frederik Glads gate',
  'Frederik Haslunds gate',
  'Frederik Stangs gate',
  'Frederiks gate',
  'Fredheimveien',
  'Fredrik Petersens gate',
  'Fredrik Selmers vei',
  'Fredrikke Qvams gate',
  'Fredriksborgveien',
  'Fredveien',
  'Freidigveien',
  'Frenningfaret',
  'Frennings vei',
  'Freserveien',
  'Frichs gate',
  'Fridtjof Nansens plass',
  'Fridtjof Nansens vei',
  'Fridtjovs gate',
  'Frierveien',
  'Friggs vei',
  'Friis\' gate',
  'Frimanns gate',
  'Frits Kiærs vei',
  'Fritzners gate',
  'Frodes vei',
  'Frogner plass',
  'Frogner terrasse',
  'Frognerseterveien',
  'Frognerstranda',
  'Frognerveien',
  'Frostveien',
  'Fru Kroghs brygge',
  'Frydenbergbakken',
  'Frydenbergveien',
  'Frydenlundgata',
  'Frydens gate',
  'Frysjaveien',
  'Frølichs vei',
  'Frøensalléen',
  'Frøyas gate',
  'Frøydis\' vei',
  'Fuglehauggata',
  'Fugleliveien',
  'Furer Nymos vei',
  'Furubråtveien',
  'Furukollveien',
  'Furulundsveien',
  'Furulundtoppen',
  'Furumoen',
  'Furuset allé',
  'Furusetveien',
  'Furustien',
  'Furuveien',
  'Fyrstikkalléen',
  'Fyrstikkbakken',
  'Fådveien',
  'Gabbi Lunds vei',
  'Gabels gate',
  'Galgeberg',
  'Gamle Brennavei',
  'Gamle Bygdevei',
  'Gamle Enebakkvei',
  'Gamle Fossumvei',
  'Gamle Heggelivei',
  'Gamle Herregårdsvei',
  'Gamle Hovsetervei',
  'Gamle Kjelsåsvei',
  'Gamle Leirdalsvei',
  'Gamle Madserud allé',
  'Gamle Maridalsvei',
  'Gamle Strømsvei',
  'Gamle Trondheimsveien',
  'Gamlehagen',
  'Gamlelinja',
  'Gamleveien',
  'Gange-Rolvs gate',
  'Gangstuveien',
  'Gardeveien',
  'Gartnerveien',
  'Garver Ytteborgs vei',
  'Gaupefaret',
  'Gaustadalléen',
  'Gaustadveien',
  'Geitmyrsveien',
  'General Birchs gate',
  'General Krohgs vei',
  'General Ruges vei',
  'Generallunden',
  'Geologsvingen',
  'Gerd Kjølaas\' plass',
  'Geviret',
  'Gildevangen',
  'Gimle terrasse',
  'Gimleveien',
  'Gina Krogs vei',
  'Giskehagen',
  'Gisle Johnsons plass',
  'Gisles vei',
  'Gjennomfaret',
  'Gjenveien',
  'Gjerdesmutten',
  'Gjerdrums vei',
  'Gjøaveien',
  'Gjøkbakken',
  'Gjørstads gate',
  'Gjøvikgata',
  'Glacisgata',
  'Gladengveien',
  'Glads vei',
  'Gladvoll terrasse',
  'Gladvollveien',
  'Glimmersvingen',
  'Glimmerveien',
  'Glitreveien',
  'Glückstads gate',
  'Godals vei',
  'Godheimveien',
  'Godlia parksti',
  'Godliasvingen',
  'Godliaveien',
  'Golfstubben',
  'Granbergstubben',
  'Grandeveien',
  'Granebakken',
  'Granhekkveien',
  'Granittveien',
  'Grankollveien',
  'Grankvisten',
  'Granliveien',
  'Gransdalen',
  'Granstangen',
  'Granstuveien',
  'Gransveien',
  'Grantunet',
  'Granveien',
  'Grasveien',
  'Gravdalsveien',
  'Grefsen allé',
  'Grefsenkollveien',
  'Grefsentunet',
  'Grefsenveien',
  'Gregers Grams vei',
  'Grensen',
  'Grensestien',
  'Grensesvingen',
  'Grenseveien',
  'Grete Waitz\' plass',
  'Grev Wedels plass',
  'Greveveien',
  'Grevlinglia',
  'Grevlingveien',
  'Griffenfeldts gate',
  'Grimelundshaugen',
  'Grimelundsveien',
  'Grimstadgata',
  'Grinda',
  'Grindbakken',
  'Griniveien',
  'Grorudbakken',
  'Grorudveien',
  'Grottenveien',
  'Grubbebakken',
  'Grubbegata',
  'Gruegata',
  'Grundingen',
  'Grüners gate',
  'Grünerstubben',
  'Grusveien',
  'Gruvelia',
  'Grytebekkveien',
  'Gryteveien',
  'Grønland',
  'Grønlands torg',
  'Grønlandsleiret',
  'Grønlibakken',
  'Grønliveien',
  'Grønmoveien',
  'Grønnegata',
  'Grønsundveien',
  'Grønvoll allé',
  'Grøttumsveien',
  'Gråbrødreveien',
  'Grågåsveien',
  'Graahbakken',
  'Gråkamveien',
  'Gråseterveien',
  'Gråsteinveien',
  'Guldberglia',
  'Guldbergs vei',
  'Gulleråsveien',
  'Gullhaug torg',
  'Gullhaugveien',
  'Gullkroken',
  'Gunhilds gate',
  'Gunnar Johnsons vei',
  'Gunnar Schjelderups vei',
  'Gunnars vei',
  'Gunnulvs vei',
  'Gurinestubben',
  'Guristuveien',
  'Gustav Bloms gate',
  'Gustav Heibergs vei',
  'Gustav Jensens gate',
  'Gustav Vigelands vei',
  'Gustavs gate',
  'Guvernørens vei',
  'Gydas vei',
  'Gyldenløves gate',
  'Gäbleins vei',
  'Gørbitz\' gate',
  'Gøteborggata',
  'Gårdsveien',
  'Hafrsfjordgata',
  'Hafslundveien',
  'Hagaløkka',
  'Hagan terrasse',
  'Hagapynten',
  'Hagastubben',
  'Hagaveien',
  'Hagegata',
  'Hagelundveien',
  'Hagtornveien',
  'Hakadalsveien',
  'Halfdan Kjerulfs plass',
  'Hallagerbakken',
  'Hallings gate',
  'Hallvard Bergves vei',
  'Halvdan Svartes gate',
  'Halvor Blinderens plass',
  'Halvor Schous gate',
  'Halvor Torgersens vei',
  'Hamborgveien',
  'Hammerfestgata',
  'Hammergata',
  'Hammersborggata',
  'Hammersborg torg',
  'Hammerstads gate',
  'Hanken',
  'Hans Barliens gate',
  'Hans C. Gjefles vei',
  'Hans Møller Gasmanns vei',
  'Hans Nielsen Hauges gate',
  'Hans Nielsen Hauges plass',
  'Hans Ross\' gate',
  'Hans Steinpukkers vei',
  'Hans Aanruds vei',
  'Hansegata',
  'Hansemyrveien',
  'Hansteens gate',
  'Hanåveien',
  'Harald Halvorsens vei',
  'Harald Hårdrådes plass',
  'Harald Hårfagres gate',
  'Harald Løvenskiolds vei',
  'Harald Rømckes vei',
  'Harald Sohlbergs vei',
  'Haraldrudveien',
  'Haralds vei',
  'Haraldsheimveien',
  'Haraløkka',
  'Harbitzalléen',
  'Harestien',
  'Hareveien',
  'Harry Fetts vei',
  'Hartmanns vei',
  'Hartvig Halvorsens vei',
  'Haråsveien',
  'Haslefetbakken',
  'Haslekroken',
  'Haslevangen',
  'Hasleveien',
  'Haslevollen',
  'Hasselbakken',
  'Hasselhaugveien',
  'Hauchs gate',
  'Haugakollveien',
  'Haugenstien',
  'Haugenstuveien',
  'Haugerudbakken',
  'Haugerudhagan',
  'Haugerudsenteret',
  'Haugerudtunet',
  'Haugerudveien',
  'Hauges vei',
  'Haugmannsveien',
  'Haukelibakken',
  'Hauketosvingen',
  'Hauketotoppen',
  'Hauketoveien',
  'Hauketoåsen',
  'Hausmanns gate',
  'Havna allé',
  'Havnabakken',
  'Havnehagan',
  'Havreveien',
  'Haxthausens gate',
  'Hedmarksgata',
  'Heftyebakken',
  'Hegdehaugsveien',
  'Hegermanns gate',
  'Hegermanns plass',
  'Heggelibakken',
  'Heggeliveien',
  'Heggestien',
  'Heiasvingen',
  'Heierstuveien',
  'Heikampveien',
  'Heimdalsgata',
  'Heimlibakken',
  'Hekkveien',
  'Helga Helgesens plass',
  'Helga Vaneks vei',
  'Helgesens gate',
  'Helge Sollies vei',
  'Hellerud gårdsvei',
  'Hellerud terrasse',
  'Hellerudfaret',
  'Hellerudgrenda',
  'Hellerudstubben',
  'Hellerudsvingen',
  'Hellerudveien',
  'Helleveien',
  'Hellinga',
  'Hemingveien',
  'Hemmestveitbakken',
  'Hengsengveien',
  'Henrichsens gate',
  'Henrik Backers vei',
  'Henrik Ibsens gate',
  'Henrik Klausens gate',
  'Henrik Mohns plass',
  'Henrik Sørensens vei',
  'Henriks vei',
  'Herbernveien',
  'Herman Foss\' gate',
  'Herregårdsveien',
  'Herslebs gate',
  'Hertug Skules gate',
  'Hertzbergs gate',
  'Hesjeveien',
  'Hesselbergs gate',
  'Hestehagen',
  'Hesteskoen',
  'Heyerdahls vei',
  'Hieronymus Heyerdahls gate',
  'Hjalmar Brantings vei',
  'Hjalmar Jordans vei',
  'Hjalmar Larsens gate',
  'Hjaltlandsgata',
  'Hjelms gate',
  'Hjemliveien',
  'Hjorteveien',
  'Hjørungavåggata',
  'Hjørungkroken',
  'Hjørungveien',
  'Hockeyveien',
  'Hoff terrasse',
  'Hoffsbakken',
  'Hoffselvpromenaden',
  'Hoffsjef Løvenskiolds vei',
  'Hoffsveien',
  'Hofftunet',
  'Holbergs gate',
  'Holbergs plass',
  'Holgerslystveien',
  'Hollendergata',
  'Holmboes gate',
  'Holmendammen terrasse',
  'Holmenenga',
  'Holmengrenda',
  'Holmenhaugen',
  'Holmenkollveien',
  'Holmens gate',
  'Holmensletta',
  'Holmenveien',
  'Holmestrandgata',
  'Holmlia senter vei',
  'Holmliaveien',
  'Holmliveien',
  'Holmsåsen',
  'Holmveien',
  'Holsteinveien',
  'Holsts gate',
  'Holsts vei',
  'Holtegata',
  'Holtveien',
  'Homansbakken',
  'Hoppveien',
  'Hornfjellveien',
  'Hortengata',
  'Hospitalsgata',
  'Hospitsveien',
  'Hovfaret',
  'Hovinveien',
  'Hovseterveien',
  'Hubroveien',
  'Huitfeldts gate',
  'Huk aveny',
  'Huk terrasse',
  'Hukenveien',
  'Hukgrenda',
  'Huldreveien',
  'Humleveien',
  'Hummerkloa',
  'Hurdalsgata',
  'Husebybakken',
  'Husebygrenda',
  'Husebysletta',
  'Husebyveien',
  'Hvitveisbakken',
  'Hyggeveien',
  'Hyllveien',
  'Høgdaveien',
  'Høgdefaret',
  'Høgtunveien',
  'Høgåsveien',
  'Hølandsgata',
  'Høvleriveien',
  'Høyboveien',
  'Høybråtenstien',
  'Høybråtenveien',
  'Høydalsveien',
  'Høyenhall plass',
  'Høyenhallsvingen',
  'Høyenhallveien',
  'Høyesteretts plass',
  'Høystakkveien',
  'Haakon Aunes vei',
  'Haakon den godes vei',
  'Haakon Tveters vei',
  'Haakon VIIs gate',
  'Håkons gate',
  'Haarklous plass',
  'Håvalds vei',
  'Haavard Martinsens vei',
  'Idas vei',
  'Idrettsveien',
  'Iduns gate',
  'Ilagata',
  'Industrigata',
  'Inga Bjørnsons vei',
  'Ingar Nilsens vei',
  'Ingeborgs gate',
  'Ingebret Andersens vei',
  'Ingegjerds vei',
  'Ingelbrecht Knudssøns gate',
  'Ingeniørveien',
  'Ingens gate',
  'Inger Hagerups plass',
  'Inges gate',
  'Ingiers vei',
  'Ingolf Ruuds vei',
  'Ingrid Bjerkås\' plass',
  'Inkognitogata',
  'Inkognito terrasse',
  'Innspurten',
  'Irisveien',
  'Islands gate',
  'Ivan Bjørndals gate',
  'Ivar Knutsons vei',
  'Ivar Welles vei',
  'Ivar Aasens vei',
  'Iver Olsens vei',
  'Jacob Fayes vei',
  'Jacob Hansens vei',
  'Jacob Aalls gate',
  'Jacobine Ryes vei',
  'Jansbergveien',
  'Jarbakken',
  'Jarlegata',
  'Jarlsborgveien',
  'Jegerveien',
  'Jegersborgveien',
  'Jenny Braatens plass',
  'Jens Bjelkes gate',
  'Jens Evensens plass',
  'Jensmessveien',
  'Jeppes vei',
  'Jerikoveien',
  'Jernbanetorget',
  'Jernbaneveien',
  'Jernkroken',
  'Jerpefaret',
  'Jess Carlsens gate',
  'Jetteveien',
  'Joachim Nielsens gang',
  'Johan Castbergs vei',
  'Johan Evjes vei',
  'Johan Hirsch\' vei',
  'Johan Nygaardsvolds plass',
  'Johan Scharffenbergs vei',
  'Johan Selmers gate',
  'Johan Svendsens gate',
  'Johan Svendsens plass',
  'Johan Sverdrups vei',
  'Johan Throne Holsts plass',
  'Johanne Dybwads plass',
  'Johannes Bruns gate',
  'John Brandts vei',
  'John Colletts allé',
  'John Colletts plass',
  'John G. Mattesons vei',
  'Johnny Svorkmos vei',
  'Jolly Kramer-Johansens gate',
  'Jomfrubråtveien',
  'Jomfruhagen',
  'Jomfrustien',
  'Jon P. Erliens vei',
  'Jon Smestads vei',
  'Jonas Dahls vei',
  'Jonas Reins gate',
  'Jonsokveien',
  'Jonsrudveien',
  'Jordal terrasse',
  'Jordalgata',
  'Jordbærveien',
  'Jordstjerneveien',
  'Jorines vei',
  'Josefines gate',
  'Jotunveien',
  'Jupiterveien',
  'Jutulveien',
  'Jøranstien',
  'Jørgen Løvlands gate',
  'Jørgen Moes gate',
  'Jørnsløkkveien',
  'Kabelgata',
  'Kaiekroken',
  'Kaj Munks vei',
  'Kakkelovnskroken',
  'Kalbakkfaret',
  'Kalbakkslyngen',
  'Kalbakkstubben',
  'Kalbakkveien',
  'Kallandveien',
  'Kallerudveien',
  'Kampen Hageby',
  'Kampengata',
  'Kampheimveien',
  'Kanalen',
  'Kanonhallveien',
  'Kanslergata',
  'Kantarellen terrasse',
  'Kapellveien',
  'Kaptein Oppegaards vei',
  'Karen Platous vei',
  'Karenslyst allé',
  'Karihaugveien',
  'Karistien',
  'Karistuveien',
  'Karl Andersens vei',
  'Karl Flods vei',
  'Karl Fossums vei',
  'Karl Johans gate',
  'Karl Staaffs vei',
  'Karlsborgveien',
  'Karlsrudveien',
  'Karlstadgata',
  'Karoline Kristiansens vei',
  'Karolinerveien',
  'Karsten Kjelbergs vei',
  'Karvesvingen',
  'Kasaveien',
  'Kastanjeveien',
  'Kastellbakken',
  'Kastellhagen',
  'Kastellveien',
  'Kathe Lasniks plass',
  'Katy Dues vei',
  'Kavringen brygge',
  'Keysers gate',
  'Kierschows gate',
  'Kikkutveien',
  'Kildals vei',
  'Kildeveien',
  'Kingos gate',
  'Kirkebakken',
  'Kirkegata',
  'Kirkegårdsbakken',
  'Kirkegårdsgata',
  'Kirkehaugsveien',
  'Kirkesvingen',
  'Kirkeveien',
  'Kirkeåsveien',
  'Kirsten Flagstads plass',
  'Kirsten Hansteens plass',
  'Kittel-Nielsens vei',
  'Kjeld Stubs gate',
  'Kjelsåsløkka',
  'Kjelsåsveien',
  'Kjetils vei',
  'Kjærlighetsstien',
  'Kjølberggata',
  'Klaus Torgårds vei',
  'Kleiva',
  'Klemetsrudveien',
  'Klingenberggata',
  'Klinkerveien',
  'Klokkergata',
  'Klostergata',
  'Klosterheimveien',
  'Kløfterhagen',
  'Kløverveien',
  'Kneika',
  'Knud Bryns vei',
  'Knud Graahs gate',
  'Knud Knudsens plass',
  'Knud Øyens vei',
  'Knut Alvssons vei',
  'Knut Nystedts plass',
  'Knut Valstads vei',
  'Kobbernaglen',
  'Kolderups vei',
  'Kollstien',
  'Kolonihagestien',
  'Kolstadgata',
  'Kommandør T. I. Øgrims plass',
  'Kongens gate',
  'Kongeveien',
  'Konghellegata',
  'Kong Håkon 5.s gate',
  'Konglerudtoppen',
  'Kongleveien',
  'Kongsberggata',
  'Kongshavnveien',
  'Kongsstien',
  'Kongsveien',
  'Kongsvingergata',
  'Konows gate',
  'Konsul Schjelderups vei',
  'Konvallveien',
  'Konventveien',
  'Kopperuds vei',
  'Korallveien',
  'Korsgata',
  'Korsvoll terrasse',
  'Korsvollbakken',
  'Korsvollbråtan',
  'Kortbølgen',
  'Krafts gate',
  'Krags terrasse',
  'Krags vei',
  'Kragstubben',
  'Kransen',
  'Kranveien',
  'Krebs\' gate',
  'Kringkollen',
  'Kringlebekkveien',
  'Kringsjågrenda',
  'Kringveien',
  'Kristian Auberts vei',
  'Kristian Augusts gate',
  'Kristian Bogneruds vei',
  'Kristian IVs gate',
  'Kristianiasvingen',
  'Kristiansands gate',
  'Kristine Bonnevies vei',
  'Kristinelundveien',
  'Kristins vei',
  'Kristoffer Robins vei',
  'Kristoffer Aamots gate',
  'Krogs gate',
  'Kroken',
  'Krokkleiva',
  'Krokliveien',
  'Krokstien',
  'Krokusveien',
  'Kronprinsens gate',
  'Kronprinsesse Märthas plass',
  'Kronveien',
  'Krossveien',
  'Krumgata',
  'Kruses gate',
  'Kruttveien',
  'Kryssveien',
  'Kudalsveien',
  'Kurlandstien',
  'Kurveien',
  'Kvartsveien',
  'Kvernfaret',
  'Kvernkallveien',
  'Kvernstien',
  'Kvernveien',
  'Kvistveien',
  'Kværnerveien',
  'Kyhns vei',
  'Kyrre Grepps gate',
  'Københavngata',
  'Kaare Røddes plass',
  'Kåres vei',
  'Lachmanns vei',
  'Ladeveien',
  'Lagerkroken',
  'Lakkegata',
  'Lallakroken',
  'Lambertseterveien',
  'Lambrechts\' gate',
  'Lammers\' gate',
  'Landerokollen',
  'Landeroveien',
  'Landgangen',
  'Landingsveien',
  'Landstads gate',
  'Langbølgen',
  'Langengen',
  'Langerudhaugen',
  'Langerudsvingen',
  'Langerudveien',
  'Langes gate',
  'Langgata',
  'Langkaia',
  'Langlia',
  'Langlibakken',
  'Langliveien',
  'Langmyrgrenda',
  'Langmyrveien',
  'Langretta',
  'Langs linjen',
  'Langsetveien',
  'Langteigåsen',
  'Langviksveien',
  'Langaards gate',
  'Langåsveien',
  'Larsbråtveien',
  'Larviksgata',
  'Lassons gate',
  'Laura Gundersens gate',
  'Lauvlundveien',
  'Lavrans\' vei',
  'Legatveien',
  'Leirfallsgata',
  'Leirskallbakken',
  'Leirskallen',
  'Leirskallhellinga',
  'Leirskallsvingen',
  'Leiv Eirikssons gate',
  'Lekeplassveien',
  'Lena Hiorths plass',
  'Lensmann Hiorths allé',
  'Lerdalsfaret',
  'Lerdalsgrenda',
  'Lerdalstoppen',
  'Lerdalsveien',
  'Lerkeveien',
  'Lersolveien',
  'Lettvintveien',
  'Leyrins gate',
  'Liakollveien',
  'Liaveien',
  'Libakkfaret',
  'Libakkveien',
  'Liljeveien',
  'Lille Bislett',
  'Lille Borgen vei',
  'Lille Frogner allé',
  'Lille Frøens vei',
  'Lille Grensen',
  'Lille Huseby vei',
  'Lille Stensrud',
  'Lille Stranden',
  'Lilleakerveien',
  'Lillebakken',
  'Lillebergsvingen',
  'Lillebergveien',
  'Lilleborggata',
  'Lilletorget',
  'Lillevannsveien',
  'Lilleveien',
  'Lilloe-Olsens vei',
  'Lillogata',
  'Lilloseterveien',
  'Lindbäckveien',
  'Lindealléen',
  'Lindeberglia',
  'Lindebergveien',
  'Lindebergåsen',
  'Lindemans gate',
  'Linderngata',
  'Linderudsletta',
  'Linderudveien',
  'Lindøya',
  'Linhusveien',
  'Linjebakken',
  'Linjeveien',
  'Linneaveien',
  'Linstows gate',
  'Linaaes gate',
  'Lisa Kristoffersens plass',
  'Ljabrubakken',
  'Ljabrudiagonalen',
  'Ljabrukollen terrasse',
  'Ljabruveien',
  'Ljan terrasse',
  'Ljansbakken',
  'Ljansbrukveien',
  'Lofotgata',
  'Lofsrudhøgda',
  'Lofsrudveien',
  'Lofthus terrasse',
  'Lofthusveien',
  'Lohavngata',
  'Lokkeberget',
  'Louises gate',
  'Lovisenberggata',
  'Lovisenlund',
  'Ludvig Karstens vei',
  'Luftfartsveien',
  'Lunaveien',
  'Lunden',
  'Lundliveien',
  'Lundveien',
  'Lundåsveien',
  'Lunhvileveien',
  'Lunnestien',
  'Lusetjernveien',
  'Lutvannskroken',
  'Lutvannsveien',
  'Lybekkergata',
  'Lybekkveien',
  'Lyberget',
  'Lyder Sagens gate',
  'Lyngtrekket',
  'Lyngveien',
  'Lyngåsveien',
  'Lysebuveien',
  'Lysehagan',
  'Lyseskrenten',
  'Lyseveien',
  'Lytterveien',
  'Lyveien',
  'Lærer Holes vei',
  'Løchenveien',
  'Løkkalia',
  'Løkkaskogen',
  'Løkkegangen',
  'Løkkeveien',
  'Lønneveien',
  'Lønnhaugen allé',
  'Lønnåsveien',
  'Lørenfaret',
  'Lørenvangen',
  'Lørenveien',
  'Løvenskiolds gate',
  'Løvsetdalen',
  'Løvsetfaret',
  'Løvåsveien',
  'Løypeveien',
  'Låveveien',
  'Madame Maren Juels vei',
  'Madserud allé',
  'Magnefaret',
  'Magnus Barfots gate',
  'Magnus Bergs gate',
  'Magnus Hydles vei',
  'Magnus\' gate',
  'Mailundveien',
  'Majorstuveien',
  'Malerhaugveien',
  'Malmøgata',
  'Malmøyveien',
  'Mandalls gate',
  'Manglebergveien',
  'Manglerudveien',
  'Marcus Thranes gate',
  'Margit Hansens gate',
  'Margrethe Munthes plass',
  'Margrethe Parms vei',
  'Maria Dehlis vei',
  'Mariboes gate',
  'Maridalsveien',
  'Marienlundveien',
  'Maries gate',
  'Mariholtveien',
  'Marits vei',
  'Markstien',
  'Markveien',
  'Marmorveien',
  'Marselis\' gate',
  'Marstrandgata',
  'Marsveien',
  'Marta Steinsviks vei',
  'Martha Tynes\' vei',
  'Martin Borrebekkens vei',
  'Martin Linges vei',
  'Martin Skatvedts vei',
  'Martin Strandlis vei',
  'Martinus Lørdahls plass',
  'Mastrups gate',
  'Mauritz Hansens gate',
  'Maurstien',
  'Maurtuveien',
  'Mekanikerveien',
  'Meklenborglia',
  'Meklenborgveien',
  'Meklenborgåsen',
  'Melkeveien',
  'Mellbyedalen',
  'Mellombølgen',
  'Meltzers gate',
  'Melumveien',
  'Merkurveien',
  'Messepromenaden',
  'Michael von Sundts plass',
  'Michel Nielsens vei',
  'Micheletveien',
  'Middelthuns gate',
  'Midtoddveien',
  'Midtstugrenda',
  'Midttunveien',
  'Midtveien',
  'Midtåsen',
  'Mikael Hertzbergs vei',
  'Mikjelsbakken',
  'Mikkel Doblougs gate',
  'Mikkel Revs vei',
  'Mikrobølgen',
  'Mina Beiteplukks vei',
  'Minister Ditleffs vei',
  'Minåsveien',
  'Mogata',
  'Mogens Thorsens gate',
  'Moldegata',
  'Moltke Moes vei',
  'Monolitveien',
  'Monrads gate',
  'Mons Søviks plass',
  'Montebello terrasse',
  'Montebellobakken',
  'Montebelloveien',
  'Mor Gohjertas vei',
  'Morells vei',
  'Morenestien',
  'Morgedalsvegen',
  'Mortensrudveien',
  'Mortensvingen',
  'Mosekollen',
  'Moserabben',
  'Mosse Jørgensens plass',
  'Mosseveien',
  'Motbakkene',
  'Motzfeldts gate',
  'Movassbakken',
  'Munchs gate',
  'Munkebekken',
  'Munkedamsveien',
  'Munkegata',
  'Munkelia',
  'Munkengveien',
  'Munkerudbakken',
  'Munkerudkleiva',
  'Munkerudstubben',
  'Munkerudtunet',
  'Munkerudveien',
  'Munkerudvollen',
  'Munkerudåsen',
  'Munthes gate',
  'Muselundgrenda',
  'Museumsveien',
  'Mustads vei',
  'Myklegardgata',
  'Mylskerudveien',
  'Myntfunnveien',
  'Myntgata',
  'Myrbakkveien',
  'Myrdalveien',
  'Myrerdraget',
  'Myrerskogveien',
  'Myrerveien',
  'Myrhaugen',
  'Mælosvingen',
  'Møllefaret',
  'Mølleparken',
  'Møllergata',
  'Møllerveien',
  'Møllesvingen',
  'Måkeveien',
  'Måltrostveien',
  'Mårveien',
  'Nandrups vei',
  'Nannestadgata',
  'Nebbejordet',
  'Nedre gate',
  'Nedre Kalbakkvei',
  'Nedre Prinsdals vei',
  'Nedre Rommen',
  'Nedre Silkestrå',
  'Nedre Skogvei',
  'Nedre Skøyen vei',
  'Nedre Slottsgate',
  'Nedre Stabburvei',
  'Nedre Ullern terrasse',
  'Nedre Ullevål',
  'Nedre Vaskegang',
  'Nedre Vollgate',
  'Nedslagsveien',
  'Nellikveien',
  'Neptunveien',
  'Neuberggata',
  'Nico Hambros vei',
  'Nic Waals vei',
  'Niels Henrik Abels vei',
  'Niels Juels gate',
  'Nielsenbakken',
  'Nils Bays vei',
  'Nils Collett Vogts vei',
  'Nils Hansens vei',
  'Nils Huus\' gate',
  'Nils Lauritssøns vei',
  'Nils Tollers vei',
  'Nilserudkleiva',
  'Nini Roll Ankers plass',
  'Nissens gate',
  'Nittedalgata',
  'Njåls vei',
  'Nobels gate',
  'Nonnegata',
  'Norbygata',
  'Nordahl Bruns gate',
  'Nordahl Rolfsens plass',
  'Nordalveien',
  'Nordbergbakken',
  'Nordbergveien',
  'Nordengstubben',
  'Nordengveien',
  'Norderhovgata',
  'Nordhagaveien',
  'Nordheimbakken',
  'Nordkappgata',
  'Nordlandsgata',
  'Nordlisletta',
  'Nordlisvingen',
  'Nordlitoppen',
  'Nordliveien',
  'Nordlysveien',
  'Nordmarka',
  'Nordmarkveien',
  'Nordmørgata',
  'Nordpolen',
  'Nordre Dals vei',
  'Nordre gate',
  'Nordraaks gate',
  'Nordraaks plass',
  'Nordseter terrasse',
  'Nordsetergrenda',
  'Nordseterstien',
  'Nordseterveien',
  'Nordstjerneveien',
  'Nordstrand terrasse',
  'Nordstrandveien',
  'Nordtvetbakken',
  'Nordtvetveien',
  'Nordåssløyfa',
  'Nordåsveien',
  'Noreveien',
  'Normandieplassen',
  'Normannsgata',
  'Normaveien',
  'Nuggerudveien',
  'Numedalsgata',
  'Nybrottveien',
  'Nybyggerveien',
  'Nycoveien',
  'Nydalen allé',
  'Nydalen Bruks vei',
  'Nydalsveien',
  'Nye Heggelivei',
  'Nygata',
  'Nygård terrasse',
  'Nygårds allé',
  'Nygårdsveien',
  'Nyjordeveien',
  'Nyjordstubben',
  'Nylandsveien',
  'Nylænde',
  'Nypeveien',
  'Nyquistveien',
  'Nøklesvingen',
  'Nøklevannsveien',
  'Nøkleveien',
  'Nøttekneika',
  'Nøtteveien',
  'Nåkkves vei',
  'Oberst Angells vei',
  'Oberst Rodes vei',
  'Observatorie terrasse',
  'Observatoriegata',
  'Odalsgata',
  'Odd Hassels vei',
  'Odins gate',
  'Odvar Solbergs vei',
  'Ogmunds vei',
  'Ola Narr',
  'Olaf Bulls vei',
  'Olaf Helsets vei',
  'Olaf Lørenskogens vei',
  'Olaf Ryes plass',
  'Olaf Schous vei',
  'Olafiagangen',
  'Olasrudveien',
  'Olaus Fjørtofts vei',
  'Olav Aukrusts vei',
  'Olav Bjaalands vei',
  'Olav Hegnas vei',
  'Olav Kyrres gate',
  'Olav Kyrres plass',
  'Olav M. Troviks vei',
  'Olav Nygards veg',
  'Olav Selvaags plass',
  'Olav Vs gate',
  'Olav Vs plass',
  'Olaves Hvervens vei',
  'Oldtidsveien',
  'Ole Brumms vei',
  'Ole Bulls gate',
  'Ole Deviks vei',
  'Ole Fladagers gate',
  'Ole Jacob Brochs gate',
  'Ole Messelts vei',
  'Ole Moes vei',
  'Ole Reistads vei',
  'Ole Vigs gate',
  'Ole Wingers vei',
  'Olleveien',
  'Olsens Enkes vei',
  'Oluf Onsums vei',
  'Ombergveien',
  'Omsens gate',
  'Operagata',
  'Oppegårdgata',
  'Opplandgata',
  'Oppsal terrasse',
  'Oppsalstubben',
  'Oppsaltoppen',
  'Oppsalveien',
  'Oreliveien',
  'Orionveien',
  'Orknøygata',
  'Ormsundbakken',
  'Ormsundveien',
  'Ormøybakken',
  'Orrebakken',
  'Orreskogen',
  'Orreveien',
  'Oscar Dahls vei',
  'Oscars gate',
  'Oscarshallveien',
  'Oskar Braatens gate',
  'Oskar Braatens plass',
  'Oslo gate',
  'Oslo torg',
  'Ospeskogveien',
  'Ospestien',
  'Ostadalsveien',
  'Osterhaus\' gate',
  'Othilie Tonnings vei',
  'Ottar Birtings gate',
  'Otto Blehrs vei',
  'Otto Sogns vei',
  'Otto Sverdrups gate',
  'Ove Kristiansens vei',
  'P.A. Holms vei',
  'P.A. Munchs vei',
  'P.T. Mallings vei',
  'Pans vei',
  'Pareliusveien',
  'Parkdammen',
  'Parkenga',
  'Parkveien',
  'Pasoplia',
  'Pasopsvingen',
  'Pasopveien',
  'Pastor Blaauws vei',
  'Pastor Fangens vei',
  'Paulus\' plass',
  'Pavels\' gate',
  'Pearl Engens vei',
  'Peder Ankers plass',
  'Peder Ankers vei',
  'Peder Claussøns gate',
  'Peder Grøns vei',
  'Peder Holters vei',
  'Per Gynts vei',
  'Per Krohgs vei',
  'Per Kvibergs gate',
  'Pernilles vei',
  'Persbråtan',
  'Persveien',
  'Peter Møllers vei',
  'Petersborgplassen',
  'Peter Aas\' vei',
  'Pilestien',
  'Pilestredet',
  'Pilestredet park',
  'Pilotveien',
  'Pilveien',
  'Pionerstien',
  'Planetveien',
  'Platous gate',
  'Platåveien',
  'Plogveien',
  'Pløens gate',
  'Pontoppidans gate',
  'Poppelstien',
  'Porfyrveien',
  'Postdamveien',
  'Pottemakerveien',
  'President Harbitz\' gate',
  'Presidentgata',
  'Prestegata',
  'Prestegårdsveien',
  'Prestlia',
  'Prinsdalsfaret',
  'Prinsdalskleiva',
  'Prinsens gate',
  'Prinsessealléen',
  'Prinsessens plass',
  'Priorveien',
  'Problemveien',
  'Professor Aschehougs plass',
  'Professor Birkelands vei',
  'Professor Dahls gate',
  'Professor Lochmanns gate',
  'Promenaden',
  'Prost Hallings vei',
  'Protonveien',
  'Putti Westerdals plass',
  'Paal Bergs vei',
  'Ingen gater på Q',
  '',
  'Rabakken',
  'Rabbeveien',
  'Radarveien',
  'Radioveien',
  'Ragna Maries vei',
  'Ragna Nielsens vei',
  'Ragnar Kalheims plass',
  'Ragnfrids vei',
  'Ragnhild Schibbyes vei',
  'Ranunkelveien',
  'Rappveien',
  'Raschs vei',
  'Rasmus Engers vei',
  'Rasmus Winderens vei',
  'Rasmusbakken',
  'Rathkes gate',
  'Rathkes plass',
  'Raukveien',
  'Ravnkollbakken',
  'Ravnkroken',
  'Ravnåsveien',
  'Refstad allé',
  'Refstadsvingen',
  'Refstadveien',
  'Regnbueveien',
  'Reichweins gate',
  'Reidar Kobros vei',
  'Reina',
  'Rektorhaugen',
  'Revefaret',
  'Revierstredet',
  'Ribbunggata',
  'Ribstonveien',
  'Riddervolds gate',
  'Riddervolds plass',
  'Rideveien',
  'Riflegata',
  'Riggergangen',
  'Rigmor Luihns vei',
  'Rimveien',
  'Ringgata',
  'Ringnesveien',
  'Ringshusstubben',
  'Ringshusveien',
  'Ris skolevei',
  'Risalléen',
  'Risbakken',
  'Risbekkveien',
  'Risløkkalléen',
  'Risløkkfaret',
  'Risløkkveien',
  'Risstubben',
  'Risveien',
  'Roald Amundsens gate',
  'Robert Millars vei',
  'Rodes plass',
  'Rognerudveien',
  'Rolf E. Stenersens allé',
  'Rolf Hofmos gate',
  'Rolf Hofmos plass',
  'Rolf Strangers plass',
  'Rolf Wickstrøms vei',
  'Rommibakken',
  'Rommiskogen',
  'Romsdalsgata',
  'Romsås senter',
  'Romsåsveien',
  'Rosenbergveien',
  'Rosenborggata',
  'Rosendalsveien',
  'Rosenhoffgata',
  'Rosenholmveien',
  'Rosenkrantz\' gate',
  'Rosenlundgata',
  'Roseveien',
  'Rosings gate',
  'Rosteds gate',
  'Rostockgata',
  'Roveruds gate',
  'Rubina Ranas gate',
  'Rudolf Nilsens plass',
  'Rugdeberget',
  'Rugdestien',
  'Rugdeveien',
  'Rugveien',
  'Rundhaugveien',
  'Rundingen',
  'Rundmyrveien',
  'Rundtjernveien',
  'Ruseløkkveien',
  'Rustadgrenda',
  'Rustadsaga',
  'Ruth Reeses plass',
  'Ruths vei',
  'Ryenbergveien',
  'Ryenstubben',
  'Ryensvingen',
  'Ryghs vei',
  'Røa terrasse',
  'Røahagan',
  'Røahellinga',
  'Røaknekken',
  'Røatoppen',
  'Røaveien',
  'Rødbergveien',
  'Rødbråtbakken',
  'Rødkleivfaret',
  'Rødstuveien',
  'Rødtvetkroken',
  'Rødtvetveien',
  'Røhrts vei',
  'Rønningveien',
  'Røslyngveien',
  'Rådhusgata',
  'Rådhusplassen',
  'Rådyrlia',
  'Rådyrstien',
  'Rådyrveien',
  'S.H. Lundhs vei',
  'Sagadammen',
  'Sagstukroken',
  'Sagstuveien',
  'Sagveien',
  'Sakariasveien',
  'Salm. Marius Jantzens plass',
  'Sam Eydes vei',
  'Samvirkeveien',
  'Sanatoriebakken',
  'Sandakerveien',
  'Sandefjordgata',
  'Sandermosveien',
  'Sandstuveien',
  'Sandtakveien',
  'Sandåsveien',
  'Sannergata',
  'Sarabråtveien',
  'Sarpsborggata',
  'Sars\' gate',
  'Saturnveien',
  'Saxegaardsgata',
  'Schandorffs plass',
  'Schives gate',
  'Schiøtts vei',
  'Schleppegrells gate',
  'Schous plass',
  'Schouterrassen',
  'Schultz\' gate',
  'Schwachs gate',
  'Schweigaards gate',
  'Schwensens gate',
  'Schübelers gate',
  'Schæffers gate',
  'Schønings gate',
  'Sehesteds gate',
  'Seilduksgata',
  'Seljeveien',
  'Selma Ellefsens vei',
  'Selvbyggerveien',
  'Sem Sælands vei',
  'Seterbråtveien',
  'Seterhøybakken',
  'Seterhøyveien',
  'Seterliveien',
  'Seterveien',
  'Setervollveien',
  'Setra vei',
  'Sexes gate',
  'Sidsel Sidsærks vei',
  'Siebkes gate',
  'Sigbjørn Obstfelders vei',
  'Siggerudveien',
  'Signe Nesbakkens vei',
  'Sigrid Undsets vei',
  'Sigurd Astrups vei',
  'Sigurd Hoels vei',
  'Sigurd A. Danielsens vei',
  'Sigurd Iversens vei',
  'Sigurd Johannesens vei',
  'Sigurd Lies gate',
  'Sigurd Syrs gate',
  'Sigurd Weisæths vei',
  'Sigurds gate',
  'Sigyns gate',
  'Siksakveien',
  'Siloveien',
  'Silurveien',
  'Simensbrekka',
  'Simensbråtveien',
  'Simon Darres vei',
  'Singasteinveien',
  'Sinsenterrassen',
  'Sinsenveien',
  'Siriusveien',
  'Sisikveien',
  'Sjursøya',
  'Sjøgangen',
  'Sjøgata',
  'Sjølyst plass',
  'Sjølystveien',
  'Skabos vei',
  'Skansen terrasse',
  'Skansestien',
  'Skanseveien',
  'Skappels vei',
  'Skarpsnogata',
  'Skarskroken',
  'Skausnaret',
  'Skedsmogata',
  'Skibakkeveien',
  'Skiferveien',
  'Skigardveien',
  'Skillebekk',
  'Skinnerbakken',
  'Skippergata',
  'Skjelderups gate',
  'Skjellveien',
  'Skjerstadveien',
  'Skjoldveien',
  'Skjønnhaugveien',
  'Skogbakken',
  'Skogbrynet',
  'Skogfaret',
  'Skogholtveien',
  'Skogroveien',
  'Skogryggveien',
  'Skogstien',
  'Skogvollveien',
  'Skolebakken',
  'Skolestien',
  'Skoleveien',
  'Skovveien',
  'Skrabben',
  'Skrenten',
  'Skråninga',
  'Skullerudbakken',
  'Skullerudskogen',
  'Skullerudstubben',
  'Skullerudveien',
  'Skuronnveien',
  'Skøyen allé',
  'Skøyen terrasse',
  'Skøyen torg',
  'Skøyenbakken',
  'Skøyenbrynet',
  'Skøyenkneika',
  'Skøyenkroken',
  'Skøyenstubben',
  'Skøyensvingen',
  'Skøyenveien',
  'Skøyenåsveien',
  'Skådalsveien',
  'Slalåmveien',
  'Sledemeien',
  'Slemdalsveien',
  'Slemdalsvingen',
  'Sletteløkka',
  'Slettenveien',
  'Slimeveien',
  'Slireveien',
  'Sloreåsen',
  'Slottsplassen',
  'Slyngveien',
  'Slåmotgangen',
  'Slåtteveien',
  'Smalgangen',
  'Smalvollveien',
  'Smalåkeren',
  'Smed Kjeldsens vei',
  'Smedbergveien',
  'Smedgata',
  'Smedhaugen',
  'Smedkroken',
  'Smedstusvingen',
  'Smeltedigelen',
  'Smestadhagan',
  'Smestadveien',
  'Smedveien',
  'Smithsvingen',
  'Smiuvegen',
  'Smålensgata',
  'Snargangen',
  'Snipemyrlia',
  'Snipemyrveien',
  'Snipp-Møllers vei',
  'Snippen',
  'Snorres gate',
  'Snøggveien',
  'Soelvolds vei',
  'Sofienberggata',
  'Sofies gate',
  'Sofies plass',
  'Sogneprest Asle Engers plass',
  'Sognsvannsveien',
  'Sognsveien',
  'Solbakken allé',
  'Solbakkeveien',
  'Solbergliveien',
  'Solefallsveien',
  'Soleglad',
  'Solemskogveien',
  'Solfjellsbakken',
  'Solfjellshøgda',
  'Solhauggata',
  'Solheimgata',
  'Solkroken',
  'Sollerudveien',
  'Solligata',
  'Solligrenda',
  'Solli plass',
  'Solskinnskroken',
  'Solskinnsveien',
  'Solstugrenda',
  'Solvangveien',
  'Solveien',
  'Solørgata',
  'Solåsveien',
  'Sommerrogata',
  'Sondrevegen',
  'Sonja Henies plass',
  'Sons gate',
  'Sophus Bugges plass',
  'Sophus Lies gate',
  'Sophus Aars\' vei',
  'Sorgenfrigata',
  'Spektrumveien',
  'Spikerveien',
  'Spiralen',
  'Spireaveien',
  'Sponhoggbakken',
  'Sponhoggveien',
  'Sponstugrenda',
  'Sponstuveien',
  'Sportsstien',
  'Sportsveien',
  'Sporveisgata',
  'Spångbergveien',
  'St. Edmunds vei',
  'St. Georgs vei',
  'St. Halvards gate',
  'St. Halvards plass',
  'St. Jørgens vei',
  'St. Olavs gate',
  'St. Olavs plass',
  'St. Sunnivas gate',
  'Staffeldts gate',
  'Stalheimbakken',
  'Stallerudveien',
  'Stamhusveien',
  'Standardveien',
  'Stanseveien',
  'Starveien',
  'Stasjonsallmenningen',
  'Stasjonsveien',
  'Statsråd Mathiesens vei',
  'Staudeveien',
  'Stavangergata',
  'Steenstrups gate',
  'Steinbakken',
  'Steinborgveien',
  'Steingardveien',
  'Steingrims vei',
  'Steinhammerveien',
  'Steinliveien',
  'Steinspranget',
  'Stenbråtveien',
  'Stenersgata',
  'Stensberggata',
  'Stensgata',
  'Stensrudlia',
  'Stensrudåsveien',
  'Stien',
  'Stiftamtmann Kaas\' vei',
  'Stigenga',
  'Stigengbakken',
  'Stjerneblokkveien',
  'Stjernemyrveien',
  'Stjerneveien',
  'Stockfleths gate',
  'Stockholmgata',
  'Stolmakergata',
  'Stordamsnaret',
  'Stordamveien',
  'Storgata',
  'Storkenebbveien',
  'Stormyrveien',
  'Storoveien',
  'Stortingsgata',
  'Stortings plass',
  'Stortorvet',
  'Storåssvingen',
  'Storåsveien',
  'Stovner senter',
  'Stovnerbakken',
  'Stovnerfaret',
  'Stovnerlia',
  'Stovnerveien',
  'Stranden',
  'Strandgata',
  'Strandhaugen',
  'Strandpromenaden',
  'Strømsborgveien',
  'Strømsbråtaveien',
  'Strømstadgata',
  'Strømsveien',
  'Stubben (Vestre Aker)',
  'Stubberudveien',
  'Sturlas vei',
  'Stuttvegen',
  'Styggdalen',
  'Stølsvegen',
  'Støperigata',
  'Støttumveien',
  'Stålfjæra',
  'Stålverkskroken',
  'Stålverksveien',
  'Stårputtveien',
  'Suhms gate',
  'Sukkertoppveien',
  'Sundveien',
  'Sunnmørgata',
  'Surstoffveien',
  'Svalbardveien',
  'Svaleveien',
  'Svaneveien',
  'Svartdalsveien',
  'Svartorseterveien',
  'Svarttrostveien',
  'Sveavegen',
  'Sveiserveien',
  'Sveiva',
  'Sven Bruns gate',
  'Sven Oftedals vei',
  'Svensenga',
  'Svenskerudveien',
  'Svenskestien',
  'Svenstuveien',
  'Sverdrups gate',
  'Sveriges gate',
  'Sverre Enevolds plass',
  'Sverre Iversens vei',
  'Sverre Refstads plass',
  'Sverres gate',
  'Sverres plass',
  'Sverrestien',
  'Svingen',
  'Svingen terrasse',
  'Svinten',
  'Svoldergata',
  'Svovelstikka',
  'Symreveien',
  'Syrenveien',
  'Sæveruds plass',
  'Sølve Solfengs vei',
  'Sømveien',
  'Søndre gate',
  'Søndre Rød',
  'Sørbråtveien',
  'Sørbyhaugen',
  'Søren Bulls vei',
  'Søren Jaabæks gate',
  'Sørengkaia',
  'Sørhellinga',
  'Sørkedalen',
  'Sørkedalsveien',
  'Sørligata',
  'Sørli plass',
  'Sørlibakken',
  'Sørlistien',
  'Sørliveien',
  'Sørsletta',
  'Sørstien',
  'Sørsvingen',
  'Sørumgata',
  'Sørvangen',
  'Tallbergveien',
  'Tamburveien',
  'Tangenveien',
  'Tangerudbakken',
  'Tangerudveien',
  'Tante Ulrikkes vei',
  'Teatergata',
  'Teaterplassen',
  'Teglverksgata',
  'Teglverkskroken',
  'Teisenveien',
  'Telavåggata',
  'Telemarksvingen',
  'Telesvingen',
  'Telthusbakken',
  'Tennisveien',
  'Teppaveien',
  'Terminalveien',
  'Terneveien',
  'Terningbekk',
  'Terrasseveien',
  'Tertitten',
  'Tevlingveien',
  'Th. Kittelsens vei',
  'Thaulows vei',
  'Theodor Dahls vei',
  'Theodor Kittelsens plass',
  'Theodor Løvstads vei',
  'Thereses gate',
  'Thomas Heftyes gate',
  'Thomas Heftyes plass',
  'Thomas Ulvens vei',
  'Thomles gate',
  'Thor Olsens gate',
  'Thorbjørn Egners plass',
  'Thorleif Haugs vei',
  'Thorleif Kleves torg',
  'Thorleifs allé',
  'Thorn Dønhaugs vei',
  'Thorvald Erichsens vei',
  'Thorvald Meyers gate',
  'Thulstrups gate',
  'Thunes vei',
  'Thurmanns gate',
  'Thygesons vei',
  'Tidemands gate',
  'Tingstuveien',
  'Tiriltunga',
  'Tirilveien',
  'Tittutgrenda',
  'Tittutveien',
  'Tiurveien',
  'Tjernfaret',
  'Tjernlia',
  'Tjernveien',
  'Tjonerudbakken',
  'Tjonerudveien',
  'Tjuvholmen',
  'Tjuvholmen allé',
  'Toftdahls vei',
  'Toftes gate',
  'Tokerudbekken',
  'Tokerudberget',
  'Tokeruddalen',
  'Tollbugata',
  'Tomm Murstadbakken',
  'Tonsenveien',
  'Toppen',
  'Toppåsveien',
  'Tor Jonssons veg',
  'Torbjørns vei',
  'Tordenskiolds gate',
  'Tore Hals Mejdells vei',
  'Tore Hunds vei',
  'Tores vei',
  'Torggata',
  'Torgny Segerstedts vei',
  'Torjusbakken',
  'Tormod Knutsons vei',
  'Tormods vei',
  'Tors gate',
  'Torsborgveien',
  'Torshovgata',
  'Torstølveien',
  'Torvbakkgata',
  'Tostrup terrasse',
  'Tostrups gate',
  'Totengata',
  'Traktorveien',
  'Traneveien',
  'Trappa',
  'Trasoppterrassen',
  'Trasoppveien',
  'Traverveien',
  'Trekanten',
  'Trelastgata',
  'Treschows gate',
  'Treskeveien',
  'Trestegveien',
  'Trettebakken',
  'Trimmen',
  'Trimveien',
  'Trolldalsveien',
  'Trollfaret',
  'Trollstien',
  'Trollsvingen',
  'Trollåsveien',
  'Tromsøgata',
  'Trondheimsveien',
  'Trostefaret',
  'Trosterudstien',
  'Trosterudveien',
  'Trudvangveien',
  'Trygve Lies plass',
  'Trygve Nilsens vei',
  'Trygve Ryens vei',
  'Trygve Strømbergs vei',
  'Tryms vei',
  'Trysilgata',
  'Tryvannsveien',
  'Trøndergata',
  'Tråkka',
  'Tuengen allé',
  'Tuengveien',
  'Tullinløkka',
  'Tullins gate',
  'Tunfaret',
  'Tungebråtveien',
  'Tunveien',
  'Turbinveien',
  'Turterfaret',
  'Tusentrippen',
  'Tussefaret',
  'Tverrbakken',
  'Tverrvei 2',
  'Tverrvei 3',
  'Tverrvei 4',
  'Tvetenveien',
  'Tyribakken',
  'Tyrihansveien',
  'Tyristubbveien',
  'Tyskestrandveien',
  'Tyslevkroken',
  'Tyslevveien',
  'Tønsberggata',
  'Tørtbergveien',
  'Tøyenbekken',
  'Tøyengata',
  'Tårngata',
  'Tårnveien',
  'Tåsen allé',
  'Tåsen terrase',
  'Tåsenveien',
  'Uelands gate',
  'Ugleveien',
  'Ulfstens gate',
  'Ullagerveien',
  'Ullensakergata',
  'Ullern allé',
  'Ullern Gårds vei',
  'Ullernchausseen',
  'Ullernfaret',
  'Ullernkammen',
  'Ullernkollen',
  'Ullernveien',
  'Ullevålsalléen',
  'Ullevålseterveien',
  'Ullevålsveien',
  'Ullveien',
  'Ulsholtstien',
  'Ulsholtveien',
  'Ulsrudfaret',
  'Ulsrudkollen',
  'Ulsrudveien',
  'Ulvengfaret',
  'Ulvenveien',
  'Underhaugsveien',
  'Ungers gate',
  'Universitetsgata',
  'Universitetsplassen',
  'Unnarennet',
  'Uranienborg terrasse',
  'Uranienborgveien',
  'Urtegata',
  'Urtestien',
  'Ustvedts vei',
  'Utfartsveien',
  'Utmarkveien',
  'Utsikten',
  'Utsynsveien',
  'Vahls gate',
  'Valborgs vei',
  'Valdresgata',
  'Valhallveien',
  'Valkyriegata',
  'Valkyrie plass',
  'Vallefaret',
  'Vallegata',
  'Valmueveien',
  'Vangen',
  'Vardeheimveien',
  'Vardeveien',
  'Vardøgata',
  'Vargveien',
  'Vaskeribakken',
  'Vassfaret',
  'Veita',
  'Veitvetstubben',
  'Veitvetsvingen',
  'Veitvetveien',
  'Vekslerveien',
  'Veksthusfløtten',
  'Vekterveien',
  'Vendomveien',
  'Vennerbakken',
  'Vennerliveien',
  'Vennersborgveien',
  'Venåsvegen',
  'Verkseier Furulunds vei',
  'Verksgata',
  'Verkstedveien',
  'Veslefrikkveien',
  'Veslekleiva',
  'Veslekroken',
  'Vesleveien',
  'Vestagløttveien',
  'Vestbrynet',
  'Vestbysvingen',
  'Vestbyveien',
  'Vestengsvingen',
  'Vestengveien',
  'Vesterstien',
  'Vesteråsveien',
  'Vestfoldgata',
  'Vestgrensa',
  'Vestheimgata',
  'Vestlia',
  'Vestlisvingen',
  'Vestliveien',
  'Vestre Elvebakke',
  'Vestre Haugen',
  'Vestre Holmen vei',
  'Vestveien',
  'Vetlandsfaret',
  'Vetlandsveien',
  'Vettaliveien',
  'Via Nova',
  'Vibes gate',
  'Victoria terrasse',
  'Vidars gate',
  'Vidjeveien',
  'Vidsynveien',
  'Viggo Hansteens vei',
  'Vikengata',
  'Vikingveien',
  'Vilberggrenda',
  'Vilbergveien',
  'Villaveien',
  'Vindernveien',
  'Vingolfveien',
  'Vinkelplassen',
  'Vinkelveien',
  'Vinterveien',
  'Vitaminveien',
  'Vogts gate',
  'Voksenhagen',
  'Voksenkollveien',
  'Voksenliveien',
  'Vollaveien',
  'Vollebekkveien',
  'Volvat terrasse',
  'Von der Lippes gate',
  'Von Øtkens vei',
  'Vossegata',
  'Vulkan',
  'Vækerø terrasse',
  'Vækerøveien',
  'Vækerøåsen',
  'Væringkleiva',
  'Vørterhusplassen',
  'Vøyensvingen',
  'Vågebyveien',
  'Våghalsen',
  'Vålerenggata',
  'Vålveien',
  'Våronnveien',
  'Vårsvingen',
  'Vårveien',
  'Waldemars hage',
  'Waldemar Thranes gate',
  'Wedels vei',
  'Welding Olsens vei',
  'Welhavens gate',
  'Wergelandsveien',
  'Wessels gate',
  'Wessels plass',
  'Westye Egebergs gate',
  'Wetlesens vei',
  'Wildenveybakken',
  'Wilhelm Færdens vei',
  'Wilhelm Stenersens vei',
  'Wilhelms gate',
  'Wilses gate',
  'Wilsters vei',
  'Wismargata',
  'Wolffs gate',
  'Wyllerveien',
  'Ymers vei',
  'Youngs gate',
  'Youngstorget',
  'Zahlkasserer Schafts plass',
  'Zetlitz\' gate',
  'Zinoberstubben',
  'Zinoberveien',
  'Ødegårdsveien',
  'Øgårdsveien',
  'Øivinds vei',
  'Økern torgvei',
  'Økernliveien',
  'Økernveien',
  'Ørakerfaret',
  'Ørakerstien',
  'Ørakerveien',
  'Øraveien',
  'Østbakken',
  'Østbyfaret',
  'Østbyveien',
  'Østdalsveien',
  'Østensjø terrasse',
  'Østensjøveien',
  'Østerdalsgata',
  'Østerli terrasse',
  'Østerlisvingen',
  'Østerliveien',
  'Østfoldgata',
  'Østgaards gate',
  'Østhellinga',
  'Østhornveien',
  'Østmarkveien',
  'Østre Aker vei',
  'Østre Elvebakke',
  'Østre Holmensvingen',
  'Østre vei',
  'Østreheimsveien',
  'Østvangveien',
  'Østvollveien',
  'Øverliveien',
  'Øvre gate',
  'Øvre Langås vei',
  'Øvre Ljanskoll vei',
  'Øvre Lunden',
  'Øvre Myrhaugen',
  'Øvre Prinsdals vei',
  'Øvre Skjoldvei',
  'Øvre Skogvei',
  'Øvre Slottsgate',
  'Øvre Smestadvei',
  'Øvre Stabburvei',
  'Øvre Ullern terrasse',
  'Øvre vaskegang',
  'Øvre Vollgate',
  'Øvrefoss',
  'Øvreseterveien',
  'Øysteins plass',
  'Aagots vei',
  'Åkebergveien',
  'Åkerøveien',
  'Ålesundgata',
  'Ålmoveien',
  'Ålovs vei',
  'Åmot grustak',
  'Åmotveien',
  'Årrundkroken',
  'Årrundveien',
  'Årvollia',
  'Årvollveien',
  'Åsaveien',
  'Åsbakken',
  'Åsbrekka',
  'Åsbråten',
  'Åsbråtstien',
  'Åsdalsveien',
  'Åsengata',
  'Åsensvingen',
  'Åsjordet',
  'Åslandhellinga',
  'Åslandkroken',
  'Åslandveien',
  'Åsliveien',
  'Aasmund Vinjes vei',
  'Åsryggen',
  'Åssiden terrasse',
  'Åsstubben',
  'Aasta Hansteens vei',
  'Abels gate',
  'Abildgaards gate',
  'Alfaset 2. industrivei',
  'Amunds vei',
  'Anders Winsvolds vei',
  'Asbjørnsens gate',
  'Auberts gate',
  'Axel Maurers vei',
  'Badehusgaten',
  'Bakkegata',
  'Bekkegata',
  'Bekkelagskaia',
  'Birigata',
  'Birkebeingata',
  'Bispealmenningen',
  'Bjerggaden',
  'Blåveisbakken',
  'Borgensgangen',
  'Bryggegangen',
  'Byklevegen',
  'Carl Lundgrens vei',
  'Cathinka Guldbergs vei',
  'Christen Smiths gate',
  'Clemensallmenningen',
  'Elvegata',
  'Enga',
  'Fattigstugangen',
  'Filosofgangen',
  'Flisberget',
  'Frits Thaulows gate',
  'Frognerhøiveien',
  'Gamle velodromen',
  'Gatene',
  'Geilene',
  'Grengangen',
  'Grünings løkke',
  'Grønlandskroken',
  'Grønlikleiva',
  'Güettlerbakken',
  'Gåsegangen',
  'Hans Amundsens vei',
  'Harelabbveien',
  'Haugenslettveien',
  'Havnegata',
  'Heia',
  'Heibergs gate',
  'Heiloveien',
  'Helga Helgesens gate',
  'Hågangen',
  'Haldengata',
  'Henrik Wergelands allé',
  'Holmens gate',
  'Holtermann Knudsens gate',
  'Jernbanegata',
  'Joh. H. Andresens vei',
  'Johannesgata',
  'Johan Sverdrups plass',
  'Justiskroken',
  'Kampens torg',
  'Kanten',
  'Karl den XIIs gate',
  'Karl Hals\' gate',
  'Kirkegårdsgangen',
  'Kjettingveien',
  'Kjølbergs plass',
  'Kneppebakken',
  'Kneppeskjærutstikkeren',
  'Kolleveien',
  'Krøllen',
  'Ladegangene',
  'Ladestredet',
  'Lambertstien',
  'Landstads gate',
  'Langleiken',
  'Lille Kirkebakke',
  'Ljabrochausséen',
  'Lygstergangen',
  'Løvliveien',
  'Maschmanns gate',
  'Mellemgaten',
  'Messeveien',
  'Mossegata',
  'Munthes plass',
  'Myra',
  'Nedre Hammersborggate',
  'Nellikstredet',
  'Nils Tollers gate',
  'Nordre strete',
  'Oluf Ryghs gate',
  'Persgangen',
  'Plankeveien',
  'Repslagergangen',
  'Ringeriksgata',
  'Ringsgangen',
  'Rødfyllgata',
  'Samfunnsgata',
  'Schaftegata',
  'Sjøgaten',
  'Skiensgata',
  'Skjoldgata',
  'Skolegata',
  'Skolestredet',
  'Slagtergaden',
  'Smalgangen',
  'Smedgangen',
  'Smithebakken',
  'Snekkergangen',
  'Solplassen',
  'Sorgenfribakken',
  'Stabburveien',
  'Stabellkroken',
  'Stiklestadgata',
  'Strandbakken',
  'Strandgaten',
  'Stubben (Vika)',
  'Stupinngata',
  'Sukkerhusgata',
  'Sundes gate',
  'Sverdfegerbakken',
  'Søberggangen',
  'Thygesons gate',
  'Tokerudveien',
  'Tomtegangen',
  'Tomtegata',
  'Tomtestredet',
  'Tordenskiolds plass',
  'Trasopgata',
  'Tverrvei 1',
  'Ulvestugata',
  'Vardalsgata',
  'Vaskeribakken',
  'Vestenghaugen',
  'Vestre strete',
  'Vinkelgaten',
  'Vognmannsgangen',
  'Vognmannsgata',
  'W.A. Wexels\' plass',
  'Østre strete',
  'Øvre Hammersborggate'
]

def get_address
  ADDRESSES[rand(ADDRESSES.size)]
end
